Repository capitalone/rubicon-ml, pull requests merged in 2021-03, with the labels that each got.

#15 GitHub pages workflow
  .github/workflows/publish-docs.yml
  .github/workflows/publish-package.yml
  .github/workflows/test-package.yml
  ci/environment.yml
  docs/build-docs.sh
Labels: documentation, enhancement

#16 not currently conda installable
  .github/workflows/publish-docs.yml
  README.md
  docs/build-docs.sh
  docs/source/install.rst
  rubicon/__init__.py
  setup.py
Labels: documentation

#17 handle comparison view with no params or metrics
  rubicon/ui/views/project_explorer.py
  tests/fixtures.py
  tests/integration/test_dashboard.py
Labels: bugfix

#18 add PyPi long description
  README.md
  setup.py
Labels: enhancement

#27 .github cleanup
  .github/ISSUE_TEMPLATE/documentation_request.md
  .github/pull_request_template.md
  .github/workflows/test-package.yml
Labels: enhancement

#28 add conda install instructions
  .github/workflows/publish-docs.yml
  README.md
  docs/source/install.rst
Labels: documentation

#29 conda doesnt have extras
  docs/source/install.rst
Labels: documentation

#31 add `versioneer` for versioning
  .coveragerc
  .gitattributes
  .github/ISSUE_TEMPLATE/documentation_request.md
  .github/workflows/publish-docs.yml
  .github/workflows/publish-package.yml
  .github/workflows/test-package.yml
  MANIFEST.in
  ci/environment.yml
  pyproject.toml
  rubicon/__init__.py
  rubicon/_version.py
  rubicon/repository/__init__.py
  setup.cfg
  setup.py
  versioneer.py
Labels: enhancement

#25 21 some doc feedback
  README.md
  docs/source/_static/custom.css
  docs/source/conf.py
  docs/source/faqs.rst
  docs/source/index.rst
  rubicon/client/dataframe.py
Labels: documentation

#34 Speed up install
  ci/environment.yml
  setup.py
Labels: enhancement

#40 Dataframe plot
  .gitignore
  docs/Makefile
  docs/docs-environment.yml
  docs/source/_static/custom.css
  docs/source/conf.py
  docs/source/examples.rst
  notebooks/data/revenue_data.csv
  notebooks/visualizing-logged-dataframes.ipynb
  rubicon/client/dataframe.py
Labels: feature

#41 Docs Release
  docs/docs-environment.yml
Labels: bugfix

#45 Dependency cleanup
  README.md
  ci/environment.yml
  setup.py
Labels: enhancement

#46 add logo SVG, remove unused logos
  docs/source/_static/images/rubicon_logo.svg
  docs/source/_static/images/rubicon_logo_black.png
  docs/source/_static/images/rubicon_logo_large.png
  docs/source/_static/images/rubicon_logo_white.png
Labels: enhancement

#52 try using base logger
  notebooks/developer/rubicon-pipeline.ipynb
  rubicon/sklearn/__init__.py
  rubicon/sklearn/base_logger.py
  rubicon/sklearn/logger_mapping.py
  rubicon/sklearn/loggers.py
  rubicon/sklearn/pipeline.py
Labels: enhancement

#57 don't write empty files
  rubicon/repository/local.py
  rubicon/repository/s3.py
  tests/unit/repository/test_local_repo.py
  tests/unit/repository/test_s3_repo.py
Labels: bugfix

#49 Support logging either pandas or dask dataframes
  rubicon/client/dataframe.py
  rubicon/repository/asynchronous/base.py
  rubicon/repository/base.py
  rubicon/repository/memory.py
  tests/integration/test_concurrency.py
  tests/integration/test_dataframe_logging.py
  tests/integration/test_prefect_flow.py
  tests/integration/test_rubicon.py
  tests/unit/repository/test_base_repo.py
Labels: bugfix, development
