Repository capitalone/rubicon-ml, pull requests merged in 2021-04, with the labels that each got.

#60 Support hiding cols within experiment table and comparison plot
  rubicon/ui/assets/css/project-explorer.css
  rubicon/ui/assets/css/shared.css
  rubicon/ui/model.py
  rubicon/ui/views/project_explorer.py
  tests/integration/test_dashboard.py
Labels: feature

#62 Fix dataframe
  notebooks/visualizing-logged-dataframes.ipynb
  rubicon/client/dataframe.py
  rubicon/repository/base.py
  rubicon/repository/memory.py
  tests/integration/test_dataframe_logging.py
Labels: bugfix

#63 support specifying page-size on dashboard startup
  rubicon/cli.py
  rubicon/ui/dashboard.py
  rubicon/ui/views/project_explorer.py
Labels: enhancement

#69 Add pass through for filesystem `storage_options`
  rubicon/cli.py
  rubicon/client/asynchronous/rubicon.py
  rubicon/client/config.py
  rubicon/client/rubicon.py
  rubicon/repository/asynchronous/base.py
  rubicon/repository/base.py
  rubicon/repository/memory.py
  rubicon/ui/dashboard.py
  rubicon/ui/model.py
  tests/unit/client/asynchronous/test_asyn_rubicon_client.py
  tests/unit/client/test_rubicon_client.py
Labels: enhancement

#76 59 lift integration docs
  docs/Makefile
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/integrations.rst
  notebooks/integrations/integration-git.ipynb
  notebooks/integrations/integration-prefect-workflows.ipynb
  notebooks/logging-examples/data/revenue_data.csv
  notebooks/logging-examples/logging-asynchronously.ipynb
  notebooks/logging-examples/logging-basics.ipynb
  notebooks/logging-examples/logging-concurrently.ipynb
  notebooks/logging-examples/logging-training-metadata.ipynb
  notebooks/logging-examples/visualizing-logged-dataframes.ipynb
Labels: documentation

#50 Automatic rubicon logging with sklearn pipelines
  ci/environment.yml
  docs/Makefile
  docs/source/integrations.rst
  notebooks/integrations/integration-git.ipynb
  notebooks/integrations/integration-prefect-workflows.ipynb
  notebooks/integrations/integration-sklearn.ipynb
  rubicon/sklearn/__init__.py
  rubicon/sklearn/estimator_logger.py
  rubicon/sklearn/filter_estimator_logger.py
  rubicon/sklearn/pipeline.py
  tests/fixtures.py
  tests/unit/sklearn/test_estimator_logger.py
  tests/unit/sklearn/test_filter_estimator_logger.py
  tests/unit/sklearn/test_pipeline.py
Labels: feature

#79 revisit examples
  .github/workflows/test-package.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  ci/match_version.sh
  docs/Makefile
  docs/source/_static/custom.css
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/examples.rst
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/integrations.rst
  docs/source/quick_look.rst
  environment.yml
  notebooks/README.md
  notebooks/collaboration-and-review.ipynb
  notebooks/integrations/integration-git-dashboard.png
  notebooks/integrations/integration-git.ipynb
  notebooks/integrations/integration-prefect-workflows.ipynb
  notebooks/integrations/integration-sklearn.ipynb
  notebooks/logging-examples/logging-asynchronously.ipynb
  notebooks/logging-examples/logging-basics.ipynb
  notebooks/logging-examples/logging-concurrently.ipynb
  notebooks/logging-examples/logging-concurrently.py
  notebooks/logging-examples/logging-training-metadata.ipynb
  notebooks/logging-examples/visualizing-logged-dataframes.ipynb
  notebooks/quick-look-dashboard.png
  notebooks/quick-look.ipynb
  notebooks/user-environment.yml
  rubicon/repository/asynchronous/base.py
  rubicon/ui/model.py
  rubicon/workflow/README.md
Labels: documentation, enhancement

#80 bugfix docs workflow
  docs/Makefile
  docs/build-docs.sh
  docs/docs-environment.yml
Labels: bugfix

#84 82 handle misc dotfiles
  rubicon/repository/base.py
  tests/fixtures.py
  tests/integration/test_misc_dotfiles.py
  tests/unit/client/test_dataframe_client.py
Labels: bugfix

#91 Handle misc files in async
  docs/docs-environment.yml
  environment.yml
  rubicon/repository/asynchronous/base.py
  setup.py
  tests/fixtures.py
  tests/integration/test_async_rubicon.py
  tests/unit/repository/asynchronous/test_asyn_base_repo.py
Labels: bugfix

#92 pytest warnings quickfix
  rubicon/repository/base.py
  tests/integration/test_misc_dotfiles.py
  tests/integration/test_prefect_flow.py
  tests/integration/test_rubicon.py
Labels: bugfix

#90 test example notebooks
  .pre-commit-config.yaml
  docs/Makefile
  docs/source/contributing.rst
  environment.yml
  notebooks/README.md
  notebooks/integrations/integration-prefect-workflows.ipynb
  notebooks/integrations/integration-sklearn.ipynb
  notebooks/logging-examples/data/revenue_data.csv
  notebooks/logging-examples/logging-basics.ipynb
  notebooks/logging-examples/logging-concurrently.ipynb
  notebooks/logging-examples/logging-concurrently.py
  notebooks/logging-examples/logging_concurrently.py
  notebooks/logging-examples/visualizing-logged-dataframes.ipynb
  notebooks/quick-look.ipynb
  setup.cfg
  tests/notebooks/bad-notebooks/empty-last-cell.ipynb
  tests/notebooks/bad-notebooks/not-all-executed.ipynb
  tests/notebooks/bad-notebooks/not-executed-in-order.ipynb
  tests/notebooks/bad-notebooks/not-executed.ipynb
  tests/notebooks/test_notebooks.py
  tests/notebooks/utils.py
Labels: feature
