Repository capitalone/rubicon-ml, pull requests merged in 2021-06, with the labels that each got.

#99 add runnable binder example
  README.md
  binder/environment.yml
  binder/postBuild
  binder/welcome.ipynb
  notebooks/user-environment.yml
Labels: feature

#100 address whitesource vulnerability
  docs/Makefile
  docs/build-docs.sh
  docs/source/_static/underscore.js
Labels: security fix

#104 check for `root_dir` before creating
  rubicon_ml/client/artifact.py
  rubicon_ml/repository/memory.py
  tests/unit/client/test_artifact_client.py
Labels: bugfix

#108 support date parameters
  rubicon_ml/repository/utils/json.py
  tests/unit/repository/utils/test_json.py
Labels: enhancement
