Repository capitalone/rubicon-ml, pull requests merged in 2022-09, with the labels that each got.

#262 fix intake test
  tests/unit/intake_rubicon/test_experiment.py
Labels: bugfix

#261 fix whitesource failures
  setup.cfg
Labels: security fix

#268 add tagging to artifacts
  rubicon_ml/client/artifact.py
  rubicon_ml/client/asynchronous/artifact.py
  rubicon_ml/client/asynchronous/mixin.py
  rubicon_ml/client/dataframe.py
  rubicon_ml/client/experiment.py
  rubicon_ml/client/mixin.py
  rubicon_ml/client/project.py
  rubicon_ml/domain/artifact.py
  rubicon_ml/repository/asynchronous/base.py
  rubicon_ml/repository/base.py
  tests/unit/client/test_experiment_client.py
  tests/unit/client/test_mixin_client.py
  tests/unit/client/test_project_client.py
  tests/unit/repository/asynchronous/test_asyn_base_repo.py
  tests/unit/repository/test_base_repo.py
Labels: enhancement

#275 Artifact fix
  rubicon_ml/client/mixin.py
  rubicon_ml/client/project.py
  rubicon_ml/client/utils/tags.py
  tests/unit/client/test_mixin_client.py
Labels: enhancement

#276 name cleanup
  rubicon_ml/client/experiment.py
  rubicon_ml/client/mixin.py
  rubicon_ml/client/project.py
  rubicon_ml/client/utils/tags.py
  rubicon_ml/repository/base.py
  tests/unit/repository/test_base_repo.py
Labels: enhancement

#278 271 feature tagging
  rubicon_ml/client/asynchronous/experiment.py
  rubicon_ml/client/experiment.py
  rubicon_ml/client/feature.py
  rubicon_ml/client/metric.py
  rubicon_ml/domain/feature.py
  rubicon_ml/repository/base.py
  tests/unit/client/test_experiment_client.py
  tests/unit/client/test_feature_client.py
Labels: enhancement
